base_url = "https://bitdevscordoba.github.io"
title = "BitDevs C贸rdoba"
description = "BitDevs C贸rdoba es una comunidad en el area de C贸rdoba Capital para aquellos interesados en discutir y participar en la investigaci贸n y desarrollo de Bitcoin y protocolos relacionados."
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
build_search_index = false

[markdown]
highlight_code = true

[extra]
icons = [
  {icon = "github", link = "https://github.com/bitdevscordobarg/bitdevscordoba.org"}
]

